spring.ai.openai.base-url=https://models.inference.ai.azure.com
spring.ai.openai.chat.completions-path=/chat/completions
spring.ai.openai.api-key=
spring.ai.openai.chat.options.model=gpt-5-mini

spring.ai.mistralai.base-url=https://models.github.ai/inference
spring.ai.mistralai.chat.completions-path=/chat/completions
spring.ai.mistralai.api-key=
spring.ai.mistralai.chat.options.model=mistral-ai/Codestral-2501

