spring.config.import=optional:classpath:shared-application.properties
spring.application.name=chatAutoconfiguration
server.port=8086

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.model=gpt-oss:120b-cloud
spring.ai.ollama.chat.options.temperature=0.5
spring.ai.ollama.embedding.options.model=nomic-embed-text

logging.level.org.springframework.ai=DEBUG
logging.level.ruffinjy=DEBUG